//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Plugin.TileServerCache {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TileServerCacheStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TileServerCacheStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRadar.Plugin.TileServerCache.TileServerCacheStrings", typeof(TileServerCacheStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache folder.
        /// </summary>
        public static string CacheFolderOverride {
            get {
                return ResourceManager.GetString("CacheFolderOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; does not exist.
        /// </summary>
        public static string CacheFolderOverrideDoesNotExist {
            get {
                return ResourceManager.GetString("CacheFolderOverrideDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the folder where cached tile images can be stored.
        /// </summary>
        public static string CacheFolderOverrideMustBeSupplied {
            get {
                return ResourceManager.GetString("CacheFolderOverrideMustBeSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache layer tiles.
        /// </summary>
        public static string CacheLayerTiles {
            get {
                return ResourceManager.GetString("CacheLayerTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache map tiles.
        /// </summary>
        public static string CacheMapTiles {
            get {
                return ResourceManager.GetString("CacheMapTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string DurationMS {
            get {
                return ResourceManager.GetString("DurationMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exception logged].
        /// </summary>
        public static string ExceptionLogged {
            get {
                return ResourceManager.GetString("ExceptionLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for cached tiles received over the past 10 minutes.
        /// </summary>
        public static string ExplainRecentRequestList {
            get {
                return ResourceManager.GetString("ExplainRecentRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched from tile server.
        /// </summary>
        public static string FetchedFromServer {
            get {
                return ResourceManager.GetString("FetchedFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi-Res.
        /// </summary>
        public static string HiRes {
            get {
                return ResourceManager.GetString("HiRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing from cache in offline mode.
        /// </summary>
        public static string MissingFromCacheInOfflineMode {
            get {
                return ResourceManager.GetString("MissingFromCacheInOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline mode enabled.
        /// </summary>
        public static string OfflineModeEnabled {
            get {
                return ResourceManager.GetString("OfflineModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Server Cache Options.
        /// </summary>
        public static string OptionsDialogTitle {
            get {
                return ResourceManager.GetString("OptionsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin enabled.
        /// </summary>
        public static string PluginEnabled {
            get {
                return ResourceManager.GetString("PluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Server Cache.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received (UTC).
        /// </summary>
        public static string ReceivedUTC {
            get {
                return ResourceManager.GetString("ReceivedUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Requests.
        /// </summary>
        public static string RecentRequests {
            get {
                return ResourceManager.GetString("RecentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Served from cache.
        /// </summary>
        public static string ServedFromCache {
            get {
                return ResourceManager.GetString("ServedFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile server returned status {0}.
        /// </summary>
        public static string TileServerReturnedError {
            get {
                return ResourceManager.GetString("TileServerReturnedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile server timeout.
        /// </summary>
        public static string TileServerTimeoutSeconds {
            get {
                return ResourceManager.GetString("TileServerTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        public static string TimedOut {
            get {
                return ResourceManager.GetString("TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default cache folder.
        /// </summary>
        public static string UseDefaultCacheFolder {
            get {
                return ResourceManager.GetString("UseDefaultCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Server Cache.
        /// </summary>
        public static string WebAdminMenuName {
            get {
                return ResourceManager.GetString("WebAdminMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Server Cache Recent Requests.
        /// </summary>
        public static string WebAdminRecentRequestsName {
            get {
                return ResourceManager.GetString("WebAdminRecentRequestsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
