//
//                                       PLEASE NOTE
//
// This file is generated by a T4 script. Any changes that you make to this file will be lost.
//

declare module VRS.SqlServerPlugin
{
    interface SqlServerStringsTranslatedStringsStatic
    {
        CannotConnectToDatabase:   string;
        CommandTimeout:            string;
        ConnectionString:          string;
        ConnectionStringOK:        string;
        Disabled:                  string;
        Enabled:                   string;
        EnabledFullDescription:    string;
        FakeDatabaseFileName:      string;
        OpenUpdateSchemaFile:      string;
        OptionChangesNeedARestart: string;
        PluginName:                string;
        SchemaUpdated:             string;
        SchemaUpdatedTitle:        string;
        SecondsParenthesis:        string;
        SqlServerOptions:          string;
        TestConnection:            string;
        UnspecifiedError:          string;
        UpdateSchema:              string;
        WebAdminMenuName:          string;
    }

    export var $$: SqlServerStringsTranslatedStringsStatic;
}
