UPDATE [TrackHistoryState]
SET    [TrackHistoryID] =      @TrackHistoryID
      ,[TimestampUtc] =        @TimestampUtc
      ,[SequenceNumber] =      @SequenceNumber
      ,[SignalLevel] =         @SignalLevel
      ,[ReceiverID] =          @ReceiverID
      ,[Callsign] =            @Callsign
      ,[IsCallsignSuspect] =   @IsCallsignSuspect
      ,[Latitude] =            @Latitude
      ,[Longitude] =           @Longitude
      ,[IsMlat] =              @IsMlat
      ,[IsTisb] =              @IsTisb
      ,[AltitudeFeet] =        @AltitudeFeet
      ,[AltitudeTypeID] =      @AltitudeTypeID
      ,[TargetAltitudeFeet] =  @TargetAltitudeFeet
      ,[AirPressureInHg] =     @AirPressureInHg
      ,[GroundSpeedKnots] =    @GroundSpeedKnots
      ,[SpeedTypeID] =         @SpeedTypeID
      ,[TrackDegrees] =        @TrackDegrees
      ,[TargetTrack] =         @TargetTrack
      ,[TrackIsHeading] =      @TrackIsHeading
      ,[VerticalRateFeetMin] = @VerticalRateFeetMin
      ,[VerticalRateTypeID] =  @VerticalRateTypeID
      ,[SquawkOctal] =         @SquawkOctal
      ,[IdentActive] =         @IdentActive
WHERE  [TrackHistoryStateID] = @TrackHistoryStateID;
