UPDATE [TrackHistoryState]
SET    [TrackHistoryID] =      @TrackHistoryID
      ,[TimestampUtc] =        @TimestampUtc
      ,[SequenceNumber] =      @SequenceNumber
      ,[SignalLevel] =         @SignalLevel
      ,[Callsign] =            @Callsign
      ,[IsCallsignSuspect] =   @IsCallsignSuspect
      ,[Latitude] =            @Latitude
      ,[Longitude] =           @Longitude
      ,[IsMlat] =              @IsMlat
      ,[IsTisb] =              @IsTisb
      ,[AltitudeFeet] =        @AltitudeFeet
      ,[AltitudeType] =        @AltitudeType
      ,[TargetAltitudeFeet] =  @TargetAltitudeFeet
      ,[AirPressureInHg] =     @AirPressureInHg
      ,[GroundSpeedKnots] =    @GroundSpeedKnots
      ,[SpeedType] =           @SpeedType
      ,[TrackDegrees] =        @TrackDegrees
      ,[TargetTrack] =         @TargetTrack
      ,[TrackIsHeading] =      @TrackIsHeading
      ,[VerticalRateFeetMin] = @VerticalRateFeetMin
      ,[VerticalRateType] =    @VerticalRateType
      ,[SquawkOctal] =         @SquawkOctal
      ,[IdentActive] =         @IdentActive
WHERE  [TrackHistoryStateID] = @TrackHistoryStateID;
