INSERT INTO [TrackHistoryState] (
    [TrackHistoryID]
   ,[TimestampUtc]
   ,[SequenceNumber]
   ,[SignalLevel]
   ,[Callsign]
   ,[IsCallsignSuspect]
   ,[Latitude]
   ,[Longitude]
   ,[IsMlat]
   ,[IsTisb]
   ,[AltitudeFeet]
   ,[AltitudeType]
   ,[TargetAltitudeFeet]
   ,[AirPressureInHg]
   ,[GroundSpeedKnots]
   ,[SpeedType]
   ,[TrackDegrees]
   ,[TargetTrack]
   ,[TrackIsHeading]
   ,[VerticalRateFeetMin]
   ,[VerticalRateType]
   ,[SquawkOctal]
   ,[IdentActive]
) VALUES (
    @TrackHistoryID
   ,@TimestampUtc
   ,@SequenceNumber
   ,@SignalLevel
   ,@Callsign
   ,@IsCallsignSuspect
   ,@Latitude
   ,@Longitude
   ,@IsMlat
   ,@IsTisb
   ,@AltitudeFeet
   ,@AltitudeType
   ,@TargetAltitudeFeet
   ,@AirPressureInHg
   ,@GroundSpeedKnots
   ,@SpeedType
   ,@TrackDegrees
   ,@TargetTrack
   ,@TrackIsHeading
   ,@VerticalRateFeetMin
   ,@VerticalRateType
   ,@SquawkOctal
   ,@IdentActive
);
SELECT [TrackHistoryStateID] FROM [TrackHistoryState] WHERE _ROWID_ = last_insert_rowid();
