//
//                                       PLEASE NOTE
//
// This file is generated by a T4 script. Any changes that you make to this file will be lost.
//

declare module VRS.DatabaseEditorPlugin
{
    interface DatabaseEditorStringsTranslatedStringsStatic
    {
        ImportantProperties:     string;
        Interesting:             string;
        Manufacturer:            string;
        Model:                   string;
        ModelIcao:               string;
        NoDatabaseRecord:        string;
        Notes:                   string;
        OperatorIcao:            string;
        OtherProperties:         string;
        PluginName:              string;
        Saved:                   string;
        Search:                  string;
        SerialNumber:            string;
        ServerReportedException: string;
        StatusDisabled:          string;
        StatusStatistics:        string;
        Tag:                     string;
        WebAdminMenuName:        string;
        XhrFailed:               string;
        YearBuilt:               string;
    }

    export var $$: DatabaseEditorStringsTranslatedStringsStatic;
}
