//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Database.BaseStation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRadar.Database.BaseStation.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Aircraft].*
        ///      ,(SELECT COUNT(*) FROM [Flights] WHERE [Flights].[AircraftID] = [Aircraft].[AircraftID]) AS [FlightsCount]
        ///  FROM [Aircraft]
        /// WHERE [Aircraft].[ModeS] IN @icaos;
        ///.
        /// </summary>
        internal static string Aircraft_GetAircraftAndFlightsCountByIcao {
            get {
                return ResourceManager.GetString("Aircraft_GetAircraftAndFlightsCountByIcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Note that not all columns are inserted, just the ones that VRS cares about
        ///INSERT INTO [Aircraft] (
        ///    [AircraftClass]
        ///   ,[CofACategory]
        ///   ,[CofAExpiry]
        ///   ,[Country]
        ///   ,[CurrentRegDate]
        ///   ,[DeRegDate]
        ///   ,[Engines]
        ///   ,[FirstCreated]
        ///   ,[FirstRegDate]
        ///   ,[GenericName]
        ///   ,[ICAOTypeCode]
        ///   ,[InfoUrl]
        ///   ,[Interested]
        ///   ,[LastModified]
        ///   ,[Manufacturer]
        ///   ,[ModeS]
        ///   ,[ModeSCountry]
        ///   ,[MTOW]
        ///   ,[OperatorFlagCode]
        ///   ,[OwnershipStatus]
        ///   ,[PictureUrl1]
        ///   ,[PictureUrl2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aircraft_Insert {
            get {
                return ResourceManager.GetString("Aircraft_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Note that not all columns are update, just the ones that VRS cares about
        ///UPDATE [Aircraft]
        ///   SET [AircraftClass]      = @aircraftClass
        ///      ,[CofACategory]       = @cofACategory
        ///      ,[CofAExpiry]         = @cofAExpiry
        ///      ,[Country]            = @country
        ///      ,[CurrentRegDate]     = @currentRegDate
        ///      ,[DeRegDate]          = @deRegDate
        ///      ,[Engines]            = @engines
        ///      ,[FirstCreated]       = @firstCreated
        ///      ,[FirstRegDate]       = @firstRegDate
        ///      ,[GenericName]    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aircraft_Update {
            get {
                return ResourceManager.GetString("Aircraft_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [DBHistory] (
        ///    [TimeStamp]
        ///   ,[Description]
        ///) VALUES (
        ///    @timeStamp
        ///   ,@description
        ///);
        ///SELECT [DBHistoryID] FROM [DBHistory] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string DBHistory_Insert {
            get {
                return ResourceManager.GetString("DBHistory_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [DBInfo] (
        ///    [OriginalVersion]
        ///   ,[CurrentVersion]
        ///) VALUES (
        ///    @originalVersion
        ///   ,@currentVersion
        ///);
        ///.
        /// </summary>
        internal static string DBInfo_Insert {
            get {
                return ResourceManager.GetString("DBInfo_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Flights] (
        ///    [SessionID]
        ///   ,[AircraftID]
        ///   ,[StartTime]
        ///   ,[EndTime]
        ///   ,[Callsign]
        ///   ,[NumPosMsgRec]
        ///   ,[NumADSBMsgRec]
        ///   ,[NumModeSMsgRec]
        ///   ,[NumIDMsgRec]
        ///   ,[NumSurPosMsgRec]
        ///   ,[NumAirPosMsgRec]
        ///   ,[NumAirVelMsgRec]
        ///   ,[NumSurAltMsgRec]
        ///   ,[NumSurIDMsgRec]
        ///   ,[NumAirToAirMsgRec]
        ///   ,[NumAirCallRepMsgRec]
        ///   ,[FirstIsOnGround]
        ///   ,[LastIsOnGround]
        ///   ,[FirstLat]
        ///   ,[LastLat]
        ///   ,[FirstLon]
        ///   ,[LastLon]
        ///   ,[FirstGroundSpeed]
        ///   ,[LastGroundSpeed]
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flights_Insert {
            get {
                return ResourceManager.GetString("Flights_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Flights]
        ///   SET [SessionID]              = @sessionID
        ///      ,[AircraftID]             = @aircraftID
        ///      ,[StartTime]              = @startTime
        ///      ,[EndTime]                = @endTime
        ///      ,[Callsign]               = @callsign
        ///      ,[NumPosMsgRec]           = @numPosMsgRec
        ///      ,[NumADSBMsgRec]          = @numADSBMsgRec
        ///      ,[NumModeSMsgRec]         = @numModeSMsgRec
        ///      ,[NumIDMsgRec]            = @numIDMsgRec
        ///      ,[NumSurPosMsgRec]        = @numSurPosMsgRec
        ///      ,[NumAirPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flights_Update {
            get {
                return ResourceManager.GetString("Flights_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Locations] (
        ///    [LocationName]
        ///   ,[Latitude]
        ///   ,[Longitude]
        ///   ,[Altitude]
        ///) VALUES (
        ///    @locationName
        ///   ,@latitude
        ///   ,@longitude
        ///   ,@altitude
        ///);
        ///SELECT [LocationID] FROM [Locations] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string Locations_Insert {
            get {
                return ResourceManager.GetString("Locations_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Locations]
        ///   SET [LocationName]   = @locationName
        ///      ,[Latitude]       = @latitude
        ///      ,[Longitude]      = @longitude
        ///      ,[Altitude]       = @altitude
        ///WHERE [LocationID] = @locationID;
        ///.
        /// </summary>
        internal static string Locations_Update {
            get {
                return ResourceManager.GetString("Locations_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Sessions] (
        ///    [LocationID]
        ///   ,[StartTime]
        ///   ,[EndTime]
        ///) VALUES (
        ///    @locationID
        ///   ,@startTime
        ///   ,@endTime
        ///);
        ///SELECT [SessionID] FROM [Sessions] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string Sessions_Insert {
            get {
                return ResourceManager.GetString("Sessions_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Sessions]
        ///   SET [LocationID] = @locationID
        ///      ,[StartTime]  = @startTime
        ///      ,[EndTime]    = @endTime
        ///WHERE [SessionID] = @sessionID;
        ///.
        /// </summary>
        internal static string Sessions_Update {
            get {
                return ResourceManager.GetString("Sessions_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [SystemEvents] (
        ///    [TimeStamp]
        ///   ,[App]
        ///   ,[Msg]
        ///) VALUES (
        ///    @timeStamp
        ///   ,@app
        ///   ,@msg
        ///);
        ///SELECT [SystemEventsID] FROM [SystemEvents] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string SystemEvents_Insert {
            get {
                return ResourceManager.GetString("SystemEvents_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [SystemEvents]
        ///   SET [TimeStamp]      = @timeStamp
        ///      ,[App]            = @app
        ///      ,[Msg]            = @msg
        /// WHERE [SystemEventsID] = @systemEventsID;
        ///.
        /// </summary>
        internal static string SystemEvents_Update {
            get {
                return ResourceManager.GetString("SystemEvents_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- Aircraft
        ///--
        ///CREATE TABLE IF NOT EXISTS [Aircraft]
        ///(
        ///    [AircraftID]        INTEGER PRIMARY KEY
        ///   ,[FirstCreated]      DATETIME NOT NULL
        ///   ,[LastModified]      DATETIME NOT NULL
        ///   ,[ModeS]             VARCHAR(6) NOT NULL UNIQUE
        ///   ,[ModeSCountry]      VARCHAR(24)
        ///   ,[Country]           VARCHAR(24)
        ///   ,[Registration]      VARCHAR(20)
        ///   ,[CurrentRegDate]    VARCHAR(10)
        ///   ,[PreviousID]        VARCHAR(10)
        ///   ,[FirstRegDate]      VARCHAR(10)
        ///   ,[Status]            VARCHAR(10)
        ///   ,[De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateSchema {
            get {
                return ResourceManager.GetString("UpdateSchema", resourceCulture);
            }
        }
    }
}
