-- Note that not all columns are inserted, just the ones that VRS cares about
INSERT INTO [Aircraft] (
    [AircraftClass]
   ,[CofACategory]
   ,[CofAExpiry]
   ,[Country]
   ,[CurrentRegDate]
   ,[DeRegDate]
   ,[Engines]
   ,[FirstCreated]
   ,[FirstRegDate]
   ,[GenericName]
   ,[ICAOTypeCode]
   ,[InfoUrl]
   ,[Interested]
   ,[LastModified]
   ,[Manufacturer]
   ,[ModeS]
   ,[ModeSCountry]
   ,[MTOW]
   ,[OperatorFlagCode]
   ,[OwnershipStatus]
   ,[PictureUrl1]
   ,[PictureUrl2]
   ,[PictureUrl3]
   ,[PopularName]
   ,[PreviousID]
   ,[RegisteredOwners]
   ,[Registration]
   ,[SerialNo]
   ,[Status]
   ,[TotalHours]
   ,[Type]
   ,[UserNotes]
   ,[UserString1]
   ,[UserString2]
   ,[UserString3]
   ,[UserString4]
   ,[UserString5]
   ,[UserBool1]
   ,[UserBool2]
   ,[UserBool3]
   ,[UserBool4]
   ,[UserBool5]
   ,[UserInt1]
   ,[UserInt2]
   ,[UserInt3]
   ,[UserInt4]
   ,[UserInt5]
   ,[UserTag]
   ,[YearBuilt]
) VALUES (
    @AircraftClass
   ,@CofACategory
   ,@CofAExpiry
   ,@Country
   ,@CurrentRegDate
   ,@DeRegDate
   ,@Engines
   ,@FirstCreated
   ,@FirstRegDate
   ,@GenericName
   ,@ICAOTypeCode
   ,@InfoUrl
   ,@Interested
   ,@LastModified
   ,@Manufacturer
   ,@ModeS
   ,@ModeSCountry
   ,@MTOW
   ,@OperatorFlagCode
   ,@OwnershipStatus
   ,@PictureUrl1
   ,@PictureUrl2
   ,@PictureUrl3
   ,@PopularName
   ,@PreviousID
   ,@RegisteredOwners
   ,@Registration
   ,@SerialNo
   ,@Status
   ,@TotalHours
   ,@Type
   ,@UserNotes
   ,@UserString1
   ,@UserString2
   ,@UserString3
   ,@UserString4
   ,@UserString5
   ,@UserBool1
   ,@UserBool2
   ,@UserBool3
   ,@UserBool4
   ,@UserBool5
   ,@UserInt1
   ,@UserInt2
   ,@UserInt3
   ,@UserInt4
   ,@UserInt5
   ,@UserTag
   ,@YearBuilt
);
SELECT [AircraftID] FROM [Aircraft] WHERE _ROWID_ = last_insert_rowid();
