UPDATE [Flights]
   SET [SessionID]              = @SessionID
      ,[AircraftID]             = @AircraftID
      ,[StartTime]              = @StartTime
      ,[EndTime]                = @EndTime
      ,[Callsign]               = @Callsign
      ,[NumPosMsgRec]           = @NumPosMsgRec
      ,[NumADSBMsgRec]          = @NumADSBMsgRec
      ,[NumModeSMsgRec]         = @NumModeSMsgRec
      ,[NumIDMsgRec]            = @NumIDMsgRec
      ,[NumSurPosMsgRec]        = @NumSurPosMsgRec
      ,[NumAirPosMsgRec]        = @NumAirPosMsgRec
      ,[NumAirVelMsgRec]        = @NumAirVelMsgRec
      ,[NumSurAltMsgRec]        = @NumSurAltMsgRec
      ,[NumSurIDMsgRec]         = @NumSurIDMsgRec
      ,[NumAirToAirMsgRec]      = @NumAirToAirMsgRec
      ,[NumAirCallRepMsgRec]    = @NumAirCallRepMsgRec
      ,[FirstIsOnGround]        = @FirstIsOnGround
      ,[LastIsOnGround]         = @LastIsOnGround
      ,[FirstLat]               = @FirstLat
      ,[LastLat]                = @LastLat
      ,[FirstLon]               = @FirstLon
      ,[LastLon]                = @LastLon
      ,[FirstGroundSpeed]       = @FirstGroundSpeed
      ,[LastGroundSpeed]        = @LastGroundSpeed
      ,[FirstAltitude]          = @FirstAltitude
      ,[LastAltitude]           = @LastAltitude
      ,[FirstVerticalRate]      = @FirstVerticalRate
      ,[LastVerticalRate]       = @LastVerticalRate
      ,[FirstTrack]             = @FirstTrack
      ,[LastTrack]              = @LastTrack
      ,[FirstSquawk]            = @FirstSquawk
      ,[LastSquawk]             = @LastSquawk
      ,[HadAlert]               = @HadAlert
      ,[HadEmergency]           = @HadEmergency
      ,[HadSPI]                 = @HadSpi
      ,[UserNotes]              = @UserNotes
 WHERE [FlightID] =               @FlightID;
