//
//                                       PLEASE NOTE
//
// This file is generated by a T4 script. Any changes that you make to this file will be lost.
//

declare module VRS.CustomContentPlugin
{
    interface CustomContentStringsTranslatedStringsStatic
    {
        Address:                     string;
        At:                          string;
        Body:                        string;
        Cancel:                      string;
        Delete:                      string;
        DirectoryAlreadyInUse:       string;
        DirectoryDoesNotExist:       string;
        Disabled:                    string;
        Enabled:                     string;
        EnabledNoSiteRoot:           string;
        EnabledWithSiteRoot:         string;
        End:                         string;
        ErrorCheckingFileName:       string;
        ErrorCheckingFolder:         string;
        FileDoesNotExist:            string;
        FileNameRequired:            string;
        Head:                        string;
        HtmlPage:                    string;
        Inject:                      string;
        InjectFile:                  string;
        InjectHtml:                  string;
        New:                         string;
        Of:                          string;
        OK:                          string;
        OptionsTitle:                string;
        OptionsViewTitle:            string;
        PathAndFileMissingExtension: string;
        PathAndFileMissingRoot:      string;
        PathAndFileRequired:         string;
        PluginName:                  string;
        ReplaceAndAddSiteContent:    string;
        Reset:                       string;
        ResourceImagesFolder:        string;
        SiteRootLabel:               string;
        Start:                       string;
        WebAdminMenuName:            string;
    }

    export var $$: CustomContentStringsTranslatedStringsStatic;
}
