//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Database.TrackHistoryData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRadar.Database.TrackHistoryData.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Aircraft] (
        ///    [Icao]
        ///   ,[IcaoCountryID]
        ///   ,[Registration]
        ///   ,[Serial]
        ///   ,[YearBuilt]
        ///   ,[IsInteresting]
        ///   ,[Notes]
        ///   ,[LastLookupUtc]
        ///   ,[IsMissingFromLookup]
        ///   ,[SuppressAutoUpdates]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @Icao
        ///   ,@IcaoCountryID
        ///   ,@Registration
        ///   ,@Serial
        ///   ,@YearBuilt
        ///   ,@IsInteresting
        ///   ,@Notes
        ///   ,@LastLookupUtc
        ///   ,@IsMissingFromLookup
        ///   ,@SuppressAutoUpdates
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [AircraftID] FROM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aircraft_Insert {
            get {
                return ResourceManager.GetString("Aircraft_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Aircraft]
        ///SET    [Icao] =                 @Icao
        ///      ,[IcaoCountryID] =        @IcaoCountryID
        ///      ,[Registration] =         @Registration
        ///      ,[Serial] =               @Serial
        ///      ,[YearBuilt] =            @YearBuilt
        ///      ,[IsInteresting] =        @IsInteresting
        ///      ,[Notes] =                @Notes
        ///      ,[LastLookupUtc] =        @LastLookupUtc
        ///      ,[IsMissingFromLookup] =  @IsMissingFromLookup
        ///      ,[SuppressAutoUpdates] =  @SuppressAutoUpdates
        ///      ,[UpdatedUtc] =          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aircraft_Update {
            get {
                return ResourceManager.GetString("Aircraft_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [AircraftType] (
        ///    [Icao]
        ///   ,[ManufacturerID]
        ///   ,[ModelID]
        ///   ,[EngineTypeID]
        ///   ,[EnginePlacementID]
        ///   ,[WakeTurbulenceCategoryID]
        ///   ,[EngineCount]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @Icao
        ///   ,@ManufacturerID
        ///   ,@ModelID
        ///   ,@EngineTypeID
        ///   ,@EnginePlacementID
        ///   ,@WakeTurbulenceCategoryID
        ///   ,@EngineCount
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [AircraftTypeID] FROM [AircraftType] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string AircraftType_Insert {
            get {
                return ResourceManager.GetString("AircraftType_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [AircraftType]
        ///SET    [Icao] =                     @Icao
        ///      ,[ManufacturerID] =           @ManufacturerID
        ///      ,[ModelID] =                  @ModelID
        ///      ,[EngineTypeID] =             @EngineTypeID
        ///      ,[EnginePlacementID] =        @EnginePlacementID
        ///      ,[WakeTurbulenceCategoryID] = @WakeTurbulenceCategoryID
        ///      ,[EngineCount] =              @EngineCount
        ///      ,[UpdatedUtc] =               @UpdatedUtc
        ///WHERE  [AircraftTypeID] = @AircraftTypeID;
        ///
        ///SELECT [CreatedUtc]
        ///FROM   [Air [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AircraftType_Update {
            get {
                return ResourceManager.GetString("AircraftType_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Country] (
        ///    [Name]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @Name
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [CountryID] FROM [Country] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string Country_Insert {
            get {
                return ResourceManager.GetString("Country_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Country]
        ///SET    [Name] =       @Name
        ///      ,[UpdatedUtc] = @UpdatedUtc
        ///WHERE  [CountryID] = @CountryID;
        ///
        ///SELECT [CreatedUtc]
        ///FROM   [Country]
        ///WHERE  [CountryID] = @CountryID;
        ///.
        /// </summary>
        internal static string Country_Update {
            get {
                return ResourceManager.GetString("Country_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- DatabaseVersion
        ///--
        ///CREATE TABLE IF NOT EXISTS [DatabaseVersion]
        ///(
        ///    [DatabaseVersionID] INTEGER PRIMARY KEY    -- There is only one of these and its ID is 1
        ///   ,[Version]           INTEGER NOT NULL
        ///);
        ///INSERT OR IGNORE INTO [DatabaseVersion] ([DatabaseVersionID], [Version]) VALUES (1, 1);
        ///
        ///
        ///--
        ///-- Receiver
        ///--
        ///CREATE TABLE IF NOT EXISTS [Receiver]
        ///(
        ///    [ReceiverID]    INTEGER PRIMARY KEY AUTOINCREMENT
        ///   ,[Name]          NVARCHAR(255) COLLATE NOCASE
        ///   ,[CreatedUtc]    DATETIME NOT N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Manufacturer] (
        ///    [Name]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @Name
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [ManufacturerID] FROM [Manufacturer] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string Manufacturer_Insert {
            get {
                return ResourceManager.GetString("Manufacturer_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Manufacturer]
        ///SET    [Name] =       @Name
        ///      ,[UpdatedUtc] = @UpdatedUtc
        ///WHERE  [ManufacturerID] = @ManufacturerID;
        ///
        ///SELECT [CreatedUtc]
        ///FROM   [Manufacturer]
        ///WHERE  [ManufacturerID] = @ManufacturerID;
        ///.
        /// </summary>
        internal static string Manufacturer_Update {
            get {
                return ResourceManager.GetString("Manufacturer_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Model] (
        ///    [Name]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @Name
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [ModelID] FROM [Model] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string Model_Insert {
            get {
                return ResourceManager.GetString("Model_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Model]
        ///SET    [Name] =       @Name
        ///      ,[UpdatedUtc] = @UpdatedUtc
        ///WHERE  [ModelID] = @ModelID;
        ///
        ///SELECT [CreatedUtc]
        ///FROM   [Model]
        ///WHERE  [ModelID] = @ModelID;
        ///.
        /// </summary>
        internal static string Model_Update {
            get {
                return ResourceManager.GetString("Model_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Receiver] (
        ///    [Name]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @Name
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [ReceiverID] FROM [Receiver] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string Receiver_Insert {
            get {
                return ResourceManager.GetString("Receiver_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Receiver]
        ///SET    [Name] =       @Name
        ///      ,[UpdatedUtc] = @UpdatedUtc
        ///WHERE  [ReceiverID] = @ReceiverID;
        ///
        ///SELECT [CreatedUtc]
        ///FROM   [Receiver]
        ///WHERE  [ReceiverID] = @ReceiverID;
        ///.
        /// </summary>
        internal static string Receiver_Update {
            get {
                return ResourceManager.GetString("Receiver_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA temp_store = MEMORY;
        ///
        ///CREATE TEMP TABLE _Result (
        ///    [CountTrackHistories]       INTEGER
        ///   ,[CountTrackHistoryStates]   INTEGER
        ///   ,[EarliestHistoryUtc]        DATETIME
        ///   ,[LatestHistoryUtc]          DATETIME
        ///);
        ///
        ///DELETE FROM [TrackHistoryState]
        ///WHERE  [TrackHistoryID] = @TrackHistoryID;
        ///
        ///INSERT INTO _Result (
        ///    [CountTrackHistoryStates]
        ///) VALUES (
        ///    CHANGES()
        ///);
        ///
        ///UPDATE _Result
        ///SET    [EarliestHistoryUtc] = (SELECT [CreatedUtc] FROM [TrackHistory] WHERE  [TrackHistoryID] = @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrackHistory_Delete {
            get {
                return ResourceManager.GetString("TrackHistory_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA temp_store = MEMORY;
        ///
        ///CREATE TEMP TABLE _Result (
        ///    [CountTrackHistories]       INTEGER
        ///   ,[CountTrackHistoryStates]   INTEGER
        ///   ,[EarliestHistoryUtc]        DATETIME
        ///   ,[LatestHistoryUtc]          DATETIME
        ///);
        ///
        ///DELETE FROM [TrackHistoryState]
        ///WHERE  [TrackHistoryID] IN (
        ///    SELECT [TrackHistoryID]
        ///    FROM   [TrackHistory]
        ///    WHERE  [CreatedUtc] &lt;= @threshold
        ///    AND    [IsPreserved] = 0
        ///);
        ///
        ///INSERT INTO _Result (
        ///    [CountTrackHistoryStates]
        ///) VALUES (
        ///    CHANGES()
        ///);
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrackHistory_DeleteExpired {
            get {
                return ResourceManager.GetString("TrackHistory_DeleteExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT   *
        ///FROM     [TrackHistory]
        ///WHERE    [AircraftID] = @aircraftID
        ///AND      [CreatedUtc] BETWEEN IFNULL(@startTimeInclusive, &apos;1990-01-01&apos;) AND IFNULL(@endTimeInclusive, &apos;9999-12-31&apos;)
        ///ORDER BY [CreatedUtc];
        ///.
        /// </summary>
        internal static string TrackHistory_GetByAircraftID {
            get {
                return ResourceManager.GetString("TrackHistory_GetByAircraftID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT   *
        ///FROM     [TrackHistory]
        ///WHERE    [CreatedUtc] BETWEEN IFNULL(@startTimeInclusive, &apos;1990-01-01&apos;) AND IFNULL(@endTimeInclusive, &apos;9999-12-31&apos;)
        ///ORDER BY [CreatedUtc]
        ///        ,[AircraftID];
        ///.
        /// </summary>
        internal static string TrackHistory_GetByDateRange {
            get {
                return ResourceManager.GetString("TrackHistory_GetByDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [TrackHistory] (
        ///    [AircraftID]
        ///   ,[IsPreserved]
        ///   ,[CreatedUtc]
        ///   ,[UpdatedUtc]
        ///) VALUES (
        ///    @AircraftID
        ///   ,@IsPreserved
        ///   ,@CreatedUtc
        ///   ,@UpdatedUtc
        ///);
        ///SELECT [TrackHistoryID] FROM [TrackHistory] WHERE _ROWID_ = last_insert_rowid();
        ///.
        /// </summary>
        internal static string TrackHistory_Insert {
            get {
                return ResourceManager.GetString("TrackHistory_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [TrackHistory]
        ///SET    [AircraftID] =   @AircraftID
        ///      ,[IsPreserved] =  @IsPreserved
        ///      ,[UpdatedUtc] =   @UpdatedUtc
        ///WHERE  [TrackHistoryID] = @TrackHistoryID;
        ///
        ///SELECT [CreatedUtc]
        ///FROM   [TrackHistory]
        ///WHERE  [TrackHistoryID] = @TrackHistoryID;
        ///.
        /// </summary>
        internal static string TrackHistory_Update {
            get {
                return ResourceManager.GetString("TrackHistory_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [TrackHistoryState]
        ///WHERE  [TrackHistoryStateID] = @TrackHistoryStateID;
        ///.
        /// </summary>
        internal static string TrackHistoryState_Delete {
            get {
                return ResourceManager.GetString("TrackHistoryState_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [TrackHistoryState] (
        ///    [TrackHistoryID]
        ///   ,[TimestampUtc]
        ///   ,[SequenceNumber]
        ///   ,[SignalLevel]
        ///   ,[ReceiverID]
        ///   ,[Callsign]
        ///   ,[IsCallsignSuspect]
        ///   ,[Latitude]
        ///   ,[Longitude]
        ///   ,[IsMlat]
        ///   ,[IsTisb]
        ///   ,[AltitudeFeet]
        ///   ,[AltitudeType]
        ///   ,[TargetAltitudeFeet]
        ///   ,[AirPressureInHg]
        ///   ,[GroundSpeedKnots]
        ///   ,[SpeedType]
        ///   ,[TrackDegrees]
        ///   ,[TargetTrack]
        ///   ,[TrackIsHeading]
        ///   ,[VerticalRateFeetMin]
        ///   ,[VerticalRateType]
        ///   ,[SquawkOctal]
        ///   ,[IdentAct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrackHistoryState_Insert {
            get {
                return ResourceManager.GetString("TrackHistoryState_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [TrackHistoryState]
        ///SET    [TrackHistoryID] =      @TrackHistoryID
        ///      ,[TimestampUtc] =        @TimestampUtc
        ///      ,[SequenceNumber] =      @SequenceNumber
        ///      ,[SignalLevel] =         @SignalLevel
        ///      ,[ReceiverID] =          @ReceiverID
        ///      ,[Callsign] =            @Callsign
        ///      ,[IsCallsignSuspect] =   @IsCallsignSuspect
        ///      ,[Latitude] =            @Latitude
        ///      ,[Longitude] =           @Longitude
        ///      ,[IsMlat] =              @IsMlat
        ///      ,[IsTisb] =              @IsT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrackHistoryState_Update {
            get {
                return ResourceManager.GetString("TrackHistoryState_Update", resourceCulture);
            }
        }
    }
}
