//
//                                       PLEASE NOTE
//
// This file is generated by a T4 script. Any changes that you make to this file will be lost.
//

declare module VRS.TileServerCachePlugin
{
    interface TileServerCacheStringsTranslatedStringsStatic
    {
        Abandoned:                         string;
        CacheFolderOverride:               string;
        CacheFolderOverrideDoesNotExist:   string;
        CacheFolderOverrideMustBeSupplied: string;
        CacheLayerTiles:                   string;
        CacheMapTiles:                     string;
        Cancel:                            string;
        DurationMS:                        string;
        ExceptionLogged:                   string;
        ExplainRecentRequestList:          string;
        FetchedFromServer:                 string;
        HiRes:                             string;
        MissingFromCacheInOfflineMode:     string;
        Name:                              string;
        OfflineModeEnabled:                string;
        OK:                                string;
        OptionsDialogTitle:                string;
        Outcome:                           string;
        PluginEnabled:                     string;
        PluginName:                        string;
        ReceivedUTC:                       string;
        RecentRequests:                    string;
        Seconds:                           string;
        ServedFromCache:                   string;
        TileServerReturnedError:           string;
        TileServerTimeoutSeconds:          string;
        TimedOut:                          string;
        UseDefaultCacheFolder:             string;
        Waiting:                           string;
        WebAdminMenuName:                  string;
        WebAdminRecentRequestsName:        string;
        X:                                 string;
        Y:                                 string;
        Zoom:                              string;
    }

    export var $$: TileServerCacheStringsTranslatedStringsStatic;
}
