//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Plugin.BaseStationDatabaseWriter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRadar.Plugin.BaseStationDatabaseWriter.PluginStrings", typeof(PluginStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Create Database File.
        /// </summary>
        public static string CannotCreateDatabaseFileTitle {
            get {
                return ResourceManager.GetString("CannotCreateDatabaseFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        public static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created the database file {0}.
        /// </summary>
        public static string CreatedDatabaseFile {
            get {
                return ResourceManager.GetString("CreatedDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Database File.
        /// </summary>
        public static string CreatedDatabaseFileTitle {
            get {
                return ResourceManager.GetString("CreatedDatabaseFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file already exists.
        /// </summary>
        public static string DatabaseFileAlreadyExists {
            get {
                return ResourceManager.GetString("DatabaseFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database filename.
        /// </summary>
        public static string DatabaseFileName {
            get {
                return ResourceManager.GetString("DatabaseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is currently locked by another program. Some flights may not be recorded..
        /// </summary>
        public static string DatabaseLocked {
            get {
                return ResourceManager.GetString("DatabaseLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled, updating {0}.
        /// </summary>
        public static string EnabledAndUpdatingSomething {
            get {
                return ResourceManager.GetString("EnabledAndUpdatingSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled, receiver not enabled or invalid.
        /// </summary>
        public static string EnabledBadReceiver {
            get {
                return ResourceManager.GetString("EnabledBadReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled, database not specified.
        /// </summary>
        public static string EnabledNoDatabase {
            get {
                return ResourceManager.GetString("EnabledNoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled, no receiver specified.
        /// </summary>
        public static string EnabledNoReceiver {
            get {
                return ResourceManager.GetString("EnabledNoReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled but not updating database.
        /// </summary>
        public static string EnabledNotUpdating {
            get {
                return ResourceManager.GetString("EnabledNotUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught: {0}.
        /// </summary>
        public static string ExceptionCaught {
            get {
                return ResourceManager.GetString("ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught when closing session: {0}.
        /// </summary>
        public static string ExceptionCaughtWhenClosingSession {
            get {
                return ResourceManager.GetString("ExceptionCaughtWhenClosingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught when processing message: {0}.
        /// </summary>
        public static string ExceptionCaughtWhenProcessingMessage {
            get {
                return ResourceManager.GetString("ExceptionCaughtWhenProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught when starting session: {0}.
        /// </summary>
        public static string ExceptionCaughtWhenStartingSession {
            get {
                return ResourceManager.GetString("ExceptionCaughtWhenStartingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not updating database.
        /// </summary>
        public static string NotUpdatingDatabase {
            get {
                return ResourceManager.GetString("NotUpdatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only update databases that this plugin created.
        /// </summary>
        public static string OnlyUpdateDatabasesCreatedByPlugin {
            get {
                return ResourceManager.GetString("OnlyUpdateDatabasesCreatedByPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseStation Database Writer Options.
        /// </summary>
        public static string OptionsViewTitle {
            get {
                return ResourceManager.GetString("OptionsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Writer.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Database File.
        /// </summary>
        public static string SelectDatabaseFile {
            get {
                return ResourceManager.GetString("SelectDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not exist.
        /// </summary>
        public static string SomethingDoesNotExist {
            get {
                return ResourceManager.GetString("SomethingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is zero length.
        /// </summary>
        public static string SomethingIsZeroLength {
            get {
                return ResourceManager.GetString("SomethingIsZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite details on existing aircraft.
        /// </summary>
        public static string UpdateExistingAircraft {
            get {
                return ResourceManager.GetString("UpdateExistingAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings prevent update of databases not created by plugin.
        /// </summary>
        public static string UpdatingDatabasesNotCreatedByPluginForbidden {
            get {
                return ResourceManager.GetString("UpdatingDatabasesNotCreatedByPluginForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default file name.
        /// </summary>
        public static string UseDefaultFileName {
            get {
                return ResourceManager.GetString("UseDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Writer.
        /// </summary>
        public static string WebAdminMenuName {
            get {
                return ResourceManager.GetString("WebAdminMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving online lookups will update the registration, country, serial number, year built, manufacturer, model and operator details for new and existing aircraft records that are more than 28 days old..
        /// </summary>
        public static string WriteOnlineLookupsNoticeAllAircraft {
            get {
                return ResourceManager.GetString("WriteOnlineLookupsNoticeAllAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving online lookups will update the registration, country, serial number, year built, manufacturer, model and operator details for new aircraft records..
        /// </summary>
        public static string WriteOnlineLookupsNoticeJustNew {
            get {
                return ResourceManager.GetString("WriteOnlineLookupsNoticeJustNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save online lookups in database.
        /// </summary>
        public static string WriteOnlineLookupsToDatabase {
            get {
                return ResourceManager.GetString("WriteOnlineLookupsToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving online lookups.
        /// </summary>
        public static string WritingOnlineLookupsToDatabase {
            get {
                return ResourceManager.GetString("WritingOnlineLookupsToDatabase", resourceCulture);
            }
        }
    }
}
