//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Plugin.WebAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAdminStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAdminStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugin.WebAdmin.WebAdminStrings", typeof(WebAdminStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Admin.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This screen has been changed elsewhere since you originally loaded it. Your changes were based on out-of-date information and they have not been saved..
        /// </summary>
        public static string WA_Conflicting_Update {
            get {
                return ResourceManager.GetString("WA_Conflicting_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server reported an exception, see log for details: {0}.
        /// </summary>
        public static string WA_Exception_Reported {
            get {
                return ResourceManager.GetString("WA_Exception_Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string WA_Home {
            get {
                return ResourceManager.GetString("WA_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string WA_Label_Credits {
            get {
                return ResourceManager.GetString("WA_Label_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string WA_Label_Environment {
            get {
                return ResourceManager.GetString("WA_Label_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string WA_Label_Lines {
            get {
                return ResourceManager.GetString("WA_Label_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string WA_Label_Reconnect {
            get {
                return ResourceManager.GetString("WA_Label_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset receiver range plot.
        /// </summary>
        public static string WA_Label_ResetPolarPlot {
            get {
                return ResourceManager.GetString("WA_Label_ResetPolarPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server.
        /// </summary>
        public static string WA_Label_WebServer {
            get {
                return ResourceManager.GetString("WA_Label_WebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string WA_Logout {
            get {
                return ResourceManager.GetString("WA_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has lost contact with the server and cannot continue.
        /// </summary>
        public static string WA_Lost_Contact {
            get {
                return ResourceManager.GetString("WA_Lost_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string WA_Saved {
            get {
                return ResourceManager.GetString("WA_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to end.
        /// </summary>
        public static string WA_ScrollToEnd {
            get {
                return ResourceManager.GetString("WA_ScrollToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to top.
        /// </summary>
        public static string WA_ScrollToTop {
            get {
                return ResourceManager.GetString("WA_ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page could not send a message to the server. The error was: {0}.
        /// </summary>
        public static string WA_Send_Failed {
            get {
                return ResourceManager.GetString("WA_Send_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string WA_Title_About {
            get {
                return ResourceManager.GetString("WA_Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string WA_Title_Bad {
            get {
                return ResourceManager.GetString("WA_Title_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffered.
        /// </summary>
        public static string WA_Title_Buffered {
            get {
                return ResourceManager.GetString("WA_Title_Buffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarded.
        /// </summary>
        public static string WA_Title_Discarded {
            get {
                return ResourceManager.GetString("WA_Title_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string WA_Title_Log {
            get {
                return ResourceManager.GetString("WA_Title_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string WA_Title_Main {
            get {
                return ResourceManager.GetString("WA_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string WA_Title_Messages {
            get {
                return ResourceManager.GetString("WA_Title_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string WA_Title_Options {
            get {
                return ResourceManager.GetString("WA_Title_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin: {0}.
        /// </summary>
        public static string WA_Title_PluginOptions {
            get {
                return ResourceManager.GetString("WA_Title_PluginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics - Queues.
        /// </summary>
        public static string WA_Title_Queues {
            get {
                return ResourceManager.GetString("WA_Title_Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string WA_Title_Sent {
            get {
                return ResourceManager.GetString("WA_Title_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string WA_Title_Status {
            get {
                return ResourceManager.GetString("WA_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string WA_Title_Tracking {
            get {
                return ResourceManager.GetString("WA_Title_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPnP.
        /// </summary>
        public static string WA_Title_Upnp {
            get {
                return ResourceManager.GetString("WA_Title_Upnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Radar Server.
        /// </summary>
        public static string WA_Title_VirtualRadarServer {
            get {
                return ResourceManager.GetString("WA_Title_VirtualRadarServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRS Web Admin.
        /// </summary>
        public static string WA_Title_WebAdmin {
            get {
                return ResourceManager.GetString("WA_Title_WebAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct your errors and try again.
        /// </summary>
        public static string WA_Validation_Failed {
            get {
                return ResourceManager.GetString("WA_Validation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET.
        /// </summary>
        public static string WA_Value_DotNet {
            get {
                return ResourceManager.GetString("WA_Value_DotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string WA_Value_Mono {
            get {
                return ResourceManager.GetString("WA_Value_Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Detail Lookup Log.
        /// </summary>
        public static string WS_Title_AircraftLookup_Log {
            get {
                return ResourceManager.GetString("WS_Title_AircraftLookup_Log", resourceCulture);
            }
        }
    }
}
