//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Plugin.Vatsim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VatsimStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VatsimStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRadar.Plugin.Vatsim.VatsimStrings", typeof(VatsimStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport.
        /// </summary>
        public static string Airport {
            get {
                return ResourceManager.GetString("Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport code.
        /// </summary>
        public static string AirportCode {
            get {
                return ResourceManager.GetString("AirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport.
        /// </summary>
        public static string AirportHeading {
            get {
                return ResourceManager.GetString("AirportHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assume slow aircraft are on ground.
        /// </summary>
        public static string AssumeSlowAircraftAreOnGround {
            get {
                return ResourceManager.GetString("AssumeSlowAircraftAreOnGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centred On.
        /// </summary>
        public static string CentredOnHeading {
            get {
                return ResourceManager.GetString("CentredOnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre on.
        /// </summary>
        public static string CentredOnLabel {
            get {
                return ResourceManager.GetString("CentredOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate.
        /// </summary>
        public static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string DistanceUnitHeading {
            get {
                return ResourceManager.GetString("DistanceUnitHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string DistanceUnitLabel {
            get {
                return ResourceManager.GetString("DistanceUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string FeedNameAllAircraft {
            get {
                return ResourceManager.GetString("FeedNameAllAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Name.
        /// </summary>
        public static string FeedNameHeading {
            get {
                return ResourceManager.GetString("FeedNameHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed name.
        /// </summary>
        public static string FeedNameLabel {
            get {
                return ResourceManager.GetString("FeedNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofenced Feed.
        /// </summary>
        public static string GeofencedFeed {
            get {
                return ResourceManager.GetString("GeofencedFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofenced Feeds.
        /// </summary>
        public static string GeofencedFeeds {
            get {
                return ResourceManager.GetString("GeofencedFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground speed max.
        /// </summary>
        public static string GroundSpeedMax {
            get {
                return ResourceManager.GetString("GroundSpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightHeading {
            get {
                return ResourceManager.GetString("HeightHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infer model from model type.
        /// </summary>
        public static string InferModelFromModelType {
            get {
                return ResourceManager.GetString("InferModelFromModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knots.
        /// </summary>
        public static string Knots {
            get {
                return ResourceManager.GetString("Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeHeading {
            get {
                return ResourceManager.GetString("LatitudeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeLabel {
            get {
                return ResourceManager.GetString("LatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeHeading {
            get {
                return ResourceManager.GetString("LongitudeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On ground max speed.
        /// </summary>
        public static string OnGroundSpeed {
            get {
                return ResourceManager.GetString("OnGroundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATSIM Plugin Options.
        /// </summary>
        public static string OptionsDialogTitle {
            get {
                return ResourceManager.GetString("OptionsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        public static string Pilot {
            get {
                return ResourceManager.GetString("Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot CID.
        /// </summary>
        public static string PilotCID {
            get {
                return ResourceManager.GetString("PilotCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        public static string PilotHeading {
            get {
                return ResourceManager.GetString("PilotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATSIM.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh interval.
        /// </summary>
        public static string RefreshInterval {
            get {
                return ResourceManager.GetString("RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show invalid registrations.
        /// </summary>
        public static string ShowInvalidRegistrations {
            get {
                return ResourceManager.GetString("ShowInvalidRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATSIM.
        /// </summary>
        public static string WebAdminMenuName {
            get {
                return ResourceManager.GetString("WebAdminMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthHeading {
            get {
                return ResourceManager.GetString("WidthHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
    }
}
